
CREATE TABLE `T_BASE_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(32) NOT NULL COMMENT '用户名',
  `CREATED_AT` timestamp NOT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `UPDATED_AT` timestamp NOT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(32) NOT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`),
  KEY `IDX_USER_NAME_CREATED_AT` (`USER_NAME`,`CREATED_AT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
